    # This minimal config scrape only single log file.
    # Primarily used in rpm/deb packaging where promtail service can be started during system init process.
    # And too much scraping during init process can overload the complete system.
    # https://github.com/grafana/loki/issues/11398

    server:
      http_listen_port: 9080
      grpc_listen_port: 0

    positions:
      filename: /tmp/positions.yaml

    clients:
      - url: http://localhost:3100/loki/api/v1/push

    scrape_configs:
      - job_name: journal
        journal:
          json: false
          max_age: 12h
          path: /var/log/journal
          labels:
            job: systemd-journal
        relabel_configs:
          - source_labels: ['__journal__systemd_unit']
            target_label: 'unit'
      - job_name: rss_feeds
        static_configs:
        - targets:
          - localhost
          labels:
            job: feeds
            __path__: /opt/rss-feeds-metrics/backend/rss.log
            stream: stdout